"""
Fixtures for contract model unit tests.

Provides reusable, verbose data dictionaries that match the Pydantic model schemas
for Table, TableTags, Column, ColumnTags, Contract, ContractInfo, Ownership, and Source.

Each fixture returns a plain dictionary so that tests can freely mutate it
(e.g. inject extra fields, remove required fields) without affecting other tests.

Example:
    >>> def test_table(sample_table_data):
    ...     table = Table.model_validate(sample_table_data)
    ...     assert table.name == "customer_orders"
"""

import pytest

# ---------------------------------------------------------------------------
# Column-level fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_column_tags_data() -> dict:
    """
    Provide a valid ColumnTags dictionary with a privacy tag.

    Returns:
        Dictionary matching the ColumnTags schema with a PII_HIDDEN privacy tag.

    Example:
        >>> tags = ColumnTags.model_validate(sample_column_tags_data)
        >>> assert tags.privacy.value == "PII_HIDDEN"
    """
    return {
        "privacy": "PII_HIDDEN",
    }


@pytest.fixture
def sample_column_data() -> dict:
    """
    Provide a valid Column dictionary representing a customer email column.

    The column is non-nullable and includes a privacy tag, representing a
    typical PII column in a data contract.

    Returns:
        Dictionary matching the Column schema with name, type, description,
        nullable flag, and privacy tags.

    Example:
        >>> column = Column.model_validate(sample_column_data)
        >>> assert column.name == "customer_email"
        >>> assert column.nullable is False
    """
    return {
        "name": "customer_email",
        "type": "STRING",
        "description": "Customer primary email address used for communications",
        "nullable": False,
        "tags": {
            "privacy": "PII_HIDDEN",
        },
    }


@pytest.fixture
def sample_columns_data() -> list[dict]:
    """
    Provide a list of valid Column dictionaries representing a typical order table.

    Contains four columns covering different data types and nullable settings:
    - order_id: STRING, non-nullable primary key
    - customer_name: STRING, nullable
    - order_date: DATE, non-nullable, used as a typical partition column
    - total_amount: DECIMAL(18,2), nullable

    Returns:
        List of dictionaries, each matching the Column schema.

    Example:
        >>> for col_data in sample_columns_data:
        ...     column = Column.model_validate(col_data)
        ...     print(column.name)
    """
    return [
        {
            "name": "order_id",
            "type": "STRING",
            "description": "Unique order identifier generated by the source system",
            "nullable": False,
        },
        {
            "name": "customer_name",
            "type": "STRING",
            "description": "Full name of the customer who placed the order",
            "nullable": True,
        },
        {
            "name": "order_date",
            "type": "DATE",
            "description": "Date when the order was placed in the source system",
            "nullable": False,
        },
        {
            "name": "total_amount",
            "type": "DECIMAL(18,2)",
            "description": "Total monetary value of the order in BRL",
            "nullable": True,
        },
    ]


# ---------------------------------------------------------------------------
# Table-level fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_table_tags_data() -> dict:
    """
    Provide a valid TableTags dictionary with layer and classification.

    Returns:
        Dictionary matching the TableTags schema with Gold layer
        and Classification_1 classification tag.

    Example:
        >>> tags = TableTags.model_validate(sample_table_tags_data)
        >>> assert tags.layer.value == "Gold"
    """
    return {
        "layer": "Gold",
        "classification": "Classification_1",
    }


@pytest.fixture
def sample_table_data(sample_columns_data: list[dict], sample_table_tags_data: dict) -> dict:
    """
    Provide a valid Table dictionary representing a customer orders table.

    Uses the sample_columns_data and sample_table_tags_data fixtures to build
    a complete table definition with daily refresh, 365-day retention, and
    no partitioning by default.

    Args:
        sample_columns_data: List of column dictionaries from fixture.
        sample_table_tags_data: Table tags dictionary from fixture.

    Returns:
        Dictionary matching the Table schema with all required fields.

    Example:
        >>> table = Table.model_validate(sample_table_data)
        >>> assert table.name == "customer_orders"
        >>> assert table.partitioned_by is None
    """
    return {
        "name": "customer_orders",
        "description": "Customer orders fact table with daily refresh from source ERP system",
        "refresh_frequency": "daily",
        "retention_days": 365,
        "tags": sample_table_tags_data,
        "columns": sample_columns_data,
    }


@pytest.fixture
def sample_table_data_with_partition(sample_table_data: dict) -> dict:
    """
    Provide a valid Table dictionary with partitioned_by set to order_date.

    Extends sample_table_data by adding a single partition column (order_date),
    which must exist in the columns list.

    Args:
        sample_table_data: Base table dictionary from fixture.

    Returns:
        Dictionary matching the Table schema with partitioned_by=["order_date"].

    Example:
        >>> table = Table.model_validate(sample_table_data_with_partition)
        >>> assert table.partitioned_by == ["order_date"]
    """
    sample_table_data["partitioned_by"] = ["order_date"]
    return sample_table_data


@pytest.fixture
def sample_table_data_with_multiple_partitions(sample_table_data: dict) -> dict:
    """
    Provide a valid Table dictionary with multiple partition columns.

    Extends sample_table_data by adding two partition columns (order_date
    and customer_name), both of which must exist in the columns list.

    Args:
        sample_table_data: Base table dictionary from fixture.

    Returns:
        Dictionary matching the Table schema with
        partitioned_by=["order_date", "customer_name"].

    Example:
        >>> table = Table.model_validate(sample_table_data_with_multiple_partitions)
        >>> assert len(table.partitioned_by) == 2
    """
    sample_table_data["partitioned_by"] = ["order_date", "customer_name"]
    return sample_table_data


# ---------------------------------------------------------------------------
# Ownership fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_ownership_data() -> dict:
    """
    Provide a valid Ownership dictionary with all required governance fields.

    Represents a typical ownership record for a data contract, including
    data owner, business data steward (BDS), technical data steward (TDS),
    Purview collection, portfolio, sub-domain, and business description.

    Returns:
        Dictionary matching the Ownership schema with all required fields populated.

    Example:
        >>> ownership = Ownership.model_validate(sample_ownership_data)
        >>> assert ownership.data_owner == "data.engineering@company.com"
    """
    return {
        "data_owner": "data.engineering@company.com",
        "bds": "business.steward@company.com",
        "tds": "tech.steward@company.com",
        "purview_collection": "FinanceDataCollection",
        "portfolio": "Portfolio_1",
        "sub_domain": "Sub_Domain_1",
        "business_description": "Customer orders data owned by the Finance Data Engineering team",
    }


# ---------------------------------------------------------------------------
# Source fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_source_data() -> dict:
    """
    Provide a valid Source dictionary with all optional lineage fields populated.

    Represents a SQL Server data source used for lineage tracking, including
    the Purview fully qualified name, source type, system name, and database.

    Returns:
        Dictionary matching the Source schema with all optional fields populated.

    Example:
        >>> source = Source.model_validate(sample_source_data)
        >>> assert source.type == "SQL Server"
    """
    return {
        "purview_fqn": "mssql://prod-erp-server/finance_db/dbo/orders",
        "type": "SQL Server",
        "name": "ERP Finance System",
        "database": "finance_db",
    }


# ---------------------------------------------------------------------------
# ContractInfo fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_contract_info_data() -> dict:
    """
    Provide a valid ContractInfo dictionary with name, version, and status.

    Represents the metadata section of a data contract with an active status.

    Returns:
        Dictionary matching the ContractInfo schema.

    Example:
        >>> info = ContractInfo.model_validate(sample_contract_info_data)
        >>> assert info.name == "customer_orders_v1"
    """
    return {
        "name": "customer_orders_v1",
        "version": "2.0.0",
        "status": "active",
    }


# ---------------------------------------------------------------------------
# Full Contract fixture
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_full_contract_data(
    sample_contract_info_data: dict,
    sample_ownership_data: dict,
    sample_table_data: dict,
    sample_source_data: dict,
) -> dict:
    """
    Provide a complete, valid Contract dictionary with all sections populated.

    Composes all sub-fixtures (contract info, ownership, table, source) into
    a full contract definition ready for Contract.model_validate().

    Args:
        sample_contract_info_data: Contract metadata from fixture.
        sample_ownership_data: Ownership data from fixture.
        sample_table_data: Table definition from fixture.
        sample_source_data: Source lineage data from fixture.

    Returns:
        Dictionary matching the full Contract schema with all sections.

    Example:
        >>> contract = Contract.model_validate(sample_full_contract_data)
        >>> assert contract.name == "customer_orders_v1"
        >>> assert contract.table.name == "customer_orders"
    """
    return {
        "contract": sample_contract_info_data,
        "catalog": "finance_catalog",
        "schema": "orders_schema",
        "ownership": sample_ownership_data,
        "table": sample_table_data,
        "source": sample_source_data,
    }
