"""
Fixtures for contract services unit tests.

Provides reusable data dictionaries for BuilderService tests, including
contract data with single/multiple partitions and project config data.

Example:
    >>> def test_builder(sample_builder_contract_data, sample_builder_project_config_data):
    ...     contract = Contract.model_validate(sample_builder_contract_data)
    ...     config = ProjectConfig.model_validate(sample_builder_project_config_data)
"""

import pytest


@pytest.fixture
def sample_builder_project_config_data() -> dict:
    """
    Provide a valid ProjectConfig dictionary for BuilderService tests.

    Contains dev and prod environment configurations with catalog suffixes
    that allow testing DDL generation for both environments.

    Returns:
        Dictionary matching the ProjectConfig schema with domain and environments.

    Example:
        >>> config = ProjectConfig.model_validate(sample_builder_project_config_data)
        >>> assert config.get_catalog("dev") == "analytics_catalog"
        >>> assert config.get_catalog("prod") == "analytics_catalog_prod"
    """
    return {
        "domain": {
            "name": "analytics_catalog",
            "sub_domain": "sales_schema",
            "description": "Analytics domain for sales data",
        },
        "environments": {
            "dev": {"catalog_suffix": ""},
            "prod": {"catalog_suffix": "_prod"},
        },
    }


@pytest.fixture
def sample_builder_contract_with_multiple_partitions() -> dict:
    """
    Provide a valid Contract dictionary with multiple partition columns.

    Represents an order events table partitioned by both event_date and region,
    which is a common pattern for large fact tables that benefit from
    multi-column partitioning in Delta Lake.

    The contract includes:
    - Three columns: event_id (STRING), event_date (DATE), region (STRING)
    - Partitioned by: event_date, region (two columns)
    - Daily refresh, 180-day retention, Silver layer

    Returns:
        Dictionary matching the full Contract schema with two partition columns.

    Example:
        >>> contract = Contract.model_validate(sample_builder_contract_with_multiple_partitions)
        >>> assert contract.table.partitioned_by == ["event_date", "region"]
    """
    return {
        "contract": {
            "name": "order_events_v1",
            "version": "1.0.0",
            "status": "active",
        },
        "catalog": "analytics_catalog",
        "schema": "sales_schema",
        "ownership": {
            "data_owner": "data.engineering@company.com",
            "bds": "business.steward@company.com",
            "tds": "tech.steward@company.com",
            "purview_collection": "SalesDataCollection",
            "portfolio": "Portfolio_2",
            "sub_domain": "Sub_Domain_3",
            "business_description": "Order events from the e-commerce platform partitioned by date and region",
        },
        "table": {
            "name": "order_events",
            "description": "Order events fact table from the e-commerce platform",
            "refresh_frequency": "daily",
            "retention_days": 180,
            "tags": {
                "layer": "Silver",
            },
            "columns": [
                {
                    "name": "event_id",
                    "type": "STRING",
                    "description": "Unique event identifier generated by the event pipeline",
                    "nullable": False,
                },
                {
                    "name": "event_date",
                    "type": "DATE",
                    "description": "Date when the order event was captured",
                    "nullable": False,
                },
                {
                    "name": "region",
                    "type": "STRING",
                    "description": "Geographic region code where the order originated",
                    "nullable": False,
                },
            ],
            "partitioned_by": ["event_date", "region"],
        },
    }
